import Head from "next/head";
import React from "react";
import { Button } from "../components";
import Video from "../components/Video";
import {
  CreateProfile,
  Introduce,
  Introduction,
  Tutorials,
} from "../containers";

export default function Home() {
  const [hi, setHi] = React.useState(null);

  return (
    <>
      <Head>
        <title>Sun Education</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Introduce />
        <Tutorials />
        <CreateProfile />
        <div
          onClick={() =>
            setHi(`<iframe
        width="640"
        height="360"
        src="https://short.ink/w2TOj0y6E"
        frameborder="0"
        scrolling="0"
        allowfullscreen
      ></iframe>`)
          }
        >
          {" "}
          hihiihi
        </div>
        <div dangerouslySetInnerHTML={{ __html: hi }}></div>
        <div>{hi}</div>
      </main>
    </>
  );
}
