import React from "react";
import styled from "styled-components";
import PricingWave from "../../components/Wave/PricingWave";
import Head from "next/head";
import { PricingCard, RoadmapCard, View } from "../../components";
import SwitchButton from "../../components/switchButton";
import { Text } from "../../styles";

const PricingPage = () => {
  const [pos, setPos] = React.useState(false);
  return (
    <>
      <Head>
        <title>Đăng ký học - Sun Education</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PricingWave />
      <Wrapper className="container">
        <View.Column>
          <View.Child_1>
            <View.Title
              textAlign={true}
              title="đăng ký học online"
              des="Pricing plans"
              content="Nhận quyền truy cập vào tất cả các khóa học cao cấp, hướng dẫn, tải xuống, chứng chỉ và hỗ trợ ưu tiên của chúng tôi."
            />
          </View.Child_1>
          <View.Child_1>
            <div onClick={() => setPos(!pos)}>
              <SwitchButton pos={pos} />
            </div>
          </View.Child_1>

          {/* 
          the dang ky hoc */}
          <View.Child_1>
            <PricingWrapper>
              <PricingCard />
              <PricingCard />
              <PricingCard />
            </PricingWrapper>
          </View.Child_1>
        </View.Column>
      </Wrapper>
      {/* 
      road map */}
      <Wrapper className="container">
        <View.Column>
          <View.Child_1>
            <Text.TextTitle themeText={true}>Road Map</Text.TextTitle>
          </View.Child_1>
          <View.Child_1>
            <RoadmapWrapper>
              <RoadmapCard />
              <RoadmapCard
                titleIcon="content.svg"
                colorOne="rgb(67, 22, 219)"
                colorTwo="rgb(144, 118, 231)"
                title="Content"
              />
              <RoadmapCard
                titleIcon="work.svg"
                colorOne="rgb(158, 225, 236)"
                colorTwo="rgb(229, 167, 224)"
                title="Features"
              />
            </RoadmapWrapper>
          </View.Child_1>
        </View.Column>
      </Wrapper>
    </>
  );
};

export default PricingPage;

const Wrapper = styled.section`
  display: block;
  width: 100%;
`;

const RoadmapWrapper = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 30px;
  margin: 0px auto;
  width: 100%;
  justify-items: center;
  padding: 0px 30px;
`;

const PricingWrapper = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 5px;
  margin: 30px auto;
  width: 100%;
  justify-items: center;
  padding: 0px 30px;
`;
