import React from "react";
import Head from "next/head";
import PricingWave from "../../components/Wave/PricingWave";

const index = () => {
  return (
    <>
      <Head>
        <title>Blog - Sun Education</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PricingWave />
    </>
  );
};

export default index;
